[package]
name = "decision-tree"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3

[dependencies]
clap = { version = "3.1.10", features = ["derive"] }
colored = "2.0.0"
